
try{Bootstrapper.setCurrentRuleId(10674);if(!(location+'').match(/showFooter=true|testMode=/)){console.log('stage1');var styleSheetInterval=setInterval(function(){try{var styleSheets=document.styleSheets,i=styleSheets.length,styleSheet,editableSheet;while(i--){styleSheet=styleSheets[i];if(!styleSheet.href||styleSheet.href.indexOf('//')===-1||styleSheet.href.indexOf(location.hostname)!==-1){editableSheet=styleSheet;break;}}
if(!editableSheet){return;}
function addCSSRule(selector,rule){if(editableSheet.addRule){return editableSheet.addRule(selector,rule);}else if(editableSheet.insertRule){return editableSheet.insertRule(selector+'{'+rule+'}',(editableSheet.cssRules||editableSheet.rules||[]).length);}}
function removeCSSRule(id){if(editableSheet.removeRule){return editableSheet.removeRule(id);}else if(editableSheet.deleteRule){return editableSheet.deleteRule(id);}}
var caseNum=1,url=location.href;if(url.indexOf('motorolastore.eu')!==-1){caseNum=2;}else if(url.match(/motorola-global.*.custhelp.com/)&&!url.match(/motorola-global-community--upgrade.custhelp.com/)){if(url.match(/motorola-global-.*(fr|gr|pl).custhelp.com/)){caseNum=3;}else{caseNum=4;}}else if(url.match(/uid-barney.blurdev.com|motocastid.*\.com/)&&Bootstrapper.getElementsByClassName('eu_privacy').length===0){caseNum=12;}else if(url.match(/uid-barney.blurdev.com|motocastid.*\.com/)&&Bootstrapper.getElementsByClassName('eu_privacy').length>0){caseNum=13;}
else if(url.match(/motorola.com.*CLP/)){caseNum=5;}else if(url.indexOf('motorola.com/countryselector')!==-1){caseNum=6;}else if(url.match(/motorolacareers.com/)){caseNum=7;}else if(url.match(/portal-moto/)){caseNum=8;}
else if(url.match(/mymotocast.com/)){caseNum=9;}else if(url.match(/www.motorola.com\/blog/)){caseNum=10;}else if(url.indexOf('motoactv.com')!==-1){caseNum=11;}else if(url.match(/razri.com/)){caseNum=14;}
console.log('caseNum: '+caseNum);var footerStr='PRATIQUES DE CONFIDENTIALIT.|POLITYKA PRYWAT|TWOJA PRYWATNO..|ABOUT YOUR PRIVACY|DATENSCHUTZ-HINWEIS|ACERCA DE SU PRIVACIDAD|SULLA TUA PRIVACY|(NORMATIVA\\s*)?SULLA PRIVACY|SOBRE SUA PRIVACIDADE|LA VOSTRA PRIVACY|A PROPOS DE LA VIE PRIV|SOBRE SU PRIVACIDAD|POLITYKA PRYWATNO|A PROPOS DE LA VIE PRIV|'+String.fromCharCode(931,935,917,932,921,922,913,32,924,917,32,932,927,32,913,928,927,929,929,919,932,927)+'|'+String.fromCharCode(931,935,917,932,921,922,913,32,924,917,32,932,927,32,913,928,927,929,929,919,932,927),footerRegexpStr='(<br/?>\\s*)*('+footerStr+').*',ruleId;if(caseNum===1){ruleId=addCSSRule('.copy','display: none;');addCSSRule('.crosslinks','display: none;');}else if(caseNum===2){ruleId=addCSSRule('#footer > p + p + p','display: none;');}else if(caseNum===3){ruleId=addCSSRule('.footerCopyrightSocialLinks','display: none;');}else if(caseNum===4){ruleId=addCSSRule('.footerCrossLink','display: none;');}else if(caseNum===5){ruleId=addCSSRule('#glp-mid .splitText','display: none;');}else if(caseNum===6){ruleId=addCSSRule('.bottom1 > div + div + div','display: none;');}else if(caseNum===7){ruleId=addCSSRule('.bottom1 .copyy','display: none;');}else if(caseNum===8){ruleId=addCSSRule('#eu_privacy','display: none;');}else if(caseNum===9){ruleId=addCSSRule('.eu_privacy','display: none;');}else if(caseNum===10){ruleId=addCSSRule('#footer .disclaimer','display: none;');}else if(caseNum===11){ruleId=addCSSRule('#eu-privacy, #footer > .footlinks + .footlinks','display: none;');addCSSRule('#footer > .footlinks + .footlinks + .footlinks','display: block;');}else if(caseNum===12){ruleId=addCSSRule('#footer_your_privay_table','display: none;');}else if(caseNum===13){ruleId=addCSSRule('#footer_your_privay_table','display: none;');}else if(caseNum===14){ruleId=addCSSRule('#footer-privacy-button','display: none');}
var footerRegexp=new RegExp(footerRegexpStr,'i');function getElementsByClassName(){var root=document,className='',partial=false;for(var i=0;i<arguments.length;i++){if(typeof arguments[i]=='object'){root=arguments[i];}else if(typeof arguments[i]=='string'){className=arguments[i];}else{partial=arguments[i];}}
var elements=root.getElementsByTagName('*');var retElements=[],needle=partial?new RegExp(className):new RegExp('^'+className+'$');for(var i=0;i<elements.length;i++){var tempClass=(elements[i].className||'').split(' ');for(var j=0;j<tempClass.length;j++){if(tempClass[j].match(needle)){retElements.push(elements[i]);}}}
return retElements;}
Bootstrapper.bindDOMParsed(function(){if(caseNum===1){var copyArr=getElementsByClassName('copy').concat(getElementsByClassName('crosslinks')),copy,i=0,len=copyArr.length;for(;i<len;i++){copy=copyArr[i];if(url.match(/motorola-global-community--upgrade.custhelp.com/)){var copyHtml=copy.innerHTML,footerArr=copyHtml.match(footerRegexp);if(footerArr){var footerIndex=footerArr.index,matchLen=footerArr[0].length,endIndex=copyHtml.indexOf('<br',footerIndex+matchLen);if(endIndex===-1){endIndex=copyHtml.length;}
copy.innerHTML=copyHtml.slice(0,footerIndex)+copyHtml.slice(endIndex);}}else if(url.match(/forums.motorola.com/)){var copyHtml=copy.innerHTML,footerArr=copyHtml.match(footerRegexp);if(footerArr){var footerIndex=footerArr.index,matchLen=footerArr[0].length,endIndex=copyHtml.indexOf('<br',footerIndex+matchLen);if(endIndex===-1){endIndex=copyHtml.length;}else{endIndex=copyHtml.indexOf('<br',endIndex+3);if(endIndex===-1){endIndex=copyHtml.length;}}
copy.innerHTML=copyHtml.slice(0,footerIndex)+copyHtml.slice(endIndex);}}else{if(copy.innerHTML.match(footerRegexp)){copy.innerHTML=copy.innerHTML.replace(footerRegexp,'');}}
copy.style.display='block';}}else if(caseNum===2){var footer=document.getElementById('footer')||{'getElementsByTagName':function(){}},pArr=footer.getElementsByTagName('p')||[],pElt,i=0,len=pArr.length;for(;i<len;i++){pElt=pArr[i];if(pElt.innerHTML.match(footerRegexp)){pElt.innerHTML=pElt.innerHTML.replace(footerRegexp,'');}
pElt.style.display='block';}}else if(caseNum===3){var footerArr=getElementsByClassName('footerCopyrightSocialLinks'),footer,i=0,len=footerArr.length;if(len===0){var footerArr=getElementsByClassName('footerLinksGlobal'),footer,i=0,len=footerArr.length;}
for(;i<len;i++){footer=footerArr[i];if(footer.innerHTML.match(footerRegexp)){footer.innerHTML=footer.innerHTML.replace(footerRegexp,'');}
footer.style.display='block';}}else if(caseNum===4){console.log('in case 4');var footerArr=getElementsByClassName('footerCrossLink'),footer,i=0,len=footerArr.length;if(len==0){var footerArr=getElementsByClassName('copyOuter'),footer,i=0,len=footerArr.length;}
console.log('footer array length:'+len);for(;i<len;i++){footer=footerArr[i];if(footer.innerHTML.match(footerRegexp)){footer.innerHTML=footer.innerHTML.replace(footerRegexp,'');}
footer.style.display='block';}}else if(caseNum===5){var footer=document.getElementById('glp-mid');if(footer){var splitArr=getElementsByClassName('splitText',footer),split,i=0,len=splitArr.length;for(;i<len;i++){split=splitArr[i];if(split.innerHTML.match(footerRegexp)){split.innerHTML=split.innerHTML.replace(footerRegexp,'');}
split.style.display='block';}}}else if(caseNum===6){var footer=getElementsByClassName('bottom1')[0];if(footer){var divArr=footer.getElementsByTagName('div'),div,i=0,len=divArr.length;for(;i<len;i++){div=divArr[i];if(div.innerHTML.match(footerRegexp)){div.innerHTML=div.innerHTML.replace(footerRegexp,'');}
div.style.display='block';}}}else if(caseNum===7){var footer=getElementsByClassName('bottom1')[0];if(footer){var divArr=getElementsByClassName('copyy',footer),div,divHTML,replaceIndex,i=0,len=divArr.length;for(;i<len;i++){div=divArr[i];divHTML=div.innerHTML;replaceIndex=divHTML.search(footerRegexp);if(replaceIndex!==-1){div.innerHTML=divHTML.slice(0,replaceIndex);}
div.style.display='block';}}}else if(caseNum===8){var footer=document.getElementById('eu_privacy');if(footer){footer.parentNode.removeChild(footer);}}else if(caseNum===9){var divArr=getElementsByClassName('eu_privacy'),div,i=0,len=divArr.length;for(;i<len;i++){div=divArr[i];div.innerHTML=div.innerHTML.replace(footerRegexp,'');div.style.display='block';}}else if(caseNum===10){var footer=document.getElementById('footer');if(footer){var divArr=getElementsByClassName('disclaimer',footer),div,i=0,len=divArr.length;for(;i<len;i++){div=divArr[i];div.innerHTML=div.innerHTML.replace(footerRegexp,'');div.style.display='block';}}}else if(caseNum===11){var footer=document.getElementById('eu-privacy');if(footer){footer.style.cssText='visibility: hidden; display: inline;'}
footer=document.getElementById('footer');if(footer){var divArr=getElementsByClassName('footlinks',footer),div,i=0,len=divArr.length;for(;i<len;i++){div=divArr[i];div.innerHTML=div.innerHTML.replace(footerRegexp,'');div.style.display='block';}}}else if(caseNum===12){var footer=document.getElementById('footer_your_privay_table');footer.style.cssText='display: none;'}else if(caseNum===13){var footer=document.getElementById('footer_your_privay_table');footer.style.cssText='display: none;'}else if(caseNum===14){var elem=document.getElementById('footer-privacy-button');elem.parentNode.removeChild(elem);}
removeCSSRule(ruleId);});clearInterval(styleSheetInterval);}catch(e){console.info(e);}},100);};}catch(e){Bootstrapper.reportException(e);};